name: Docker CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Auto versioning
      - name: Set Image Tag
        run: echo "TAG=v1.0.${{ github.run_number }}" >> $GITHUB_ENV

      # Step 4: Build Docker Image and tag latest
      - name: Build Docker Image
        run: |
          docker build -t naik422002/my-first-repo:${{ env.TAG }} .
          docker tag naik422002/my-first-repo:${{ env.TAG }} naik422002/my-first-repo:latest

      # Step 5: Push Docker Image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push naik422002/my-first-repo:${{ env.TAG }}
          docker push naik422002/my-first-repo:latest

      # Step 6: Test Docker Image inside CI
      - name: Test Docker Image
        run: |
          docker run --rm naik422002/my-first-repo:${{ env.TAG }}
